[book]
authors = ["Ankitects Pty Ltd and contributors"]
language = "fa"
multilingual = false
src = "src"
title = "راهنمای آنکی"

[build]
create-missing = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/noobj2/anki-manual/"
additional-css = ["css/kbd.css", "css/rtl.css"]

#[output.linkcheck]
#optional = true
#warning-policy = "warn"
#follow-web-links = true
